var JSERROR_00001="JSERROR_00001|测{0}试";
var JSCONFIRM_LOGOUT="JSCONFIRM_LOGOUT|您确定要退出系统吗?";
var JSCONFIRM_SHOP_CLOSE="JSCONFIRM_SHOP_CLOSE|您确定要闭店吗?";
var JSMSG_OVER_EDIT="JSMSG_OVER_EDIT|您确定要关闭页面吗?";
var JSMSG_LINE_SELECT="JSMSG_LINE_SELECT|请选择您要操作行！";
var JSMSG_FAIL="JSMSG_FAIL|操作失败！";
var JSMSG_SUCCESS="JSMSG_SUCCESS|操作已完成！";
var JSCONFIRM_CANCEL="JSCONFIRM_CANCEL|是否取消操作？";
var JSCONFIRM_GOON="JSCONFIRM_GOON|确定要继续执行吗？";
var JSCONFIRM_DELETE="JSCONFIRM_DELETE|确认要删除吗？";
var JSMSG_NEWS_UPLOAD_NO="JSMSG_NEWS_UPLOAD_NO|上传文件不能为空，请重新选择文件！";
var JSMSG_NEWS_UPLOAD_RELOAD="JSMSG_NEWS_UPLOAD_RELOAD|该文件已上传,是否再次上传！";
var JSMSG_NEWS_SUB_NOFILE="JSMSG_NEWS_SUB_NOFILE|参照文件不能为空，请上传文件后再提交！";
var JSCONFIRM_CHANGEGOON="JSCONFIRM_CHANGEGOON|确定要修改吗？";
//最新消息维护
var CHECK_NEWS_UPLOADFILE_EX ="CHECK_NEWS_UPLOADFILE_EX|请选择后缀名为{0}的文件!";
//店铺管理提示信息
var HOUSEMSG_EDIT_SELECT ="HOUSEMSG_EDIT_SELECT|请选择编辑行!";
var HOUSEMSG_DELETE_SELECT = "HOUSEMSG_DELETE_SELECT|请选择删除行!";
var SELECT_SHOP ="SELECT_SHOP|所属店铺不能为空,请选择!";
//店铺商品参数配置页面
var JSMSG_SHOPGOODSPARAM_WHCODE_NULL="JSMSG_SHOPGOODSPARAM_WHCODE_NULL|店铺号不能为空!";
var JSMSG_SHOPGOODSPARAM_GOODSCODE_NULL="JSMSG_SHOPGOODSPARAM_GOODSCODE_NULL|商品号不能为空!";
var JSMSG_SHOPGOODSPARAM_NUM_LIMIT="JSMSG_SHOPGOODSPARAM_NUM_LIMIT|{0}不能为空且必须为数字!";
var JSMSG_SHOPGOODSPARAM_DATE_LIMIT="JSMSG_SHOPGOODSPARAM_DATE_LIMIT|{0}格式必须为YYYYMMDD!";

var STORAGELOGIN_OUT_SHOP="STORAGELOGIN_OUT_SHOP|调出店铺不能为空,请点击取消,重新增加";
var STORAGELOGIN_IN_SHOP="STORAGELOGIN_IN_SHOP|调入店铺不能为空,请点击取消,重新增加";
var JSMSG_SHOPGOODSPARAM_DELETE_SET="JSMSG_SHOPGOODSPARAM_DELETE_SET|确认删除该设置吗?";

//经销商页面
var JSMSG_DEALER_STATE_NOTNEW="JSMSG_DEALER_STATE_NOTNEW|只能删除状态为信息已登录的经销商!";
var JSMSG_DEALER_PRO_BAIL_AMT="JSMSG_DEALER_PRO_BAIL_AMT|请填写收到保证金的金额!";
var JSMSG_DEALER_PRO_BAIL_DATE="JSMSG_DEALER_PRO_BAIL_DATE|请填写收到保证金的日期!";
var DEALERMSG_CLOSEACC_CONFIRM="DEALERMSG_CLOSEACC_CONFIRM|确定要进行闭店操作吗?";
var DEALERMSG_FROZENACC_CONFIRM="DEALERMSG_FROZENACC_CONFIRM|确定要进行冻结操作吗?";
var DEALERMSG_THAWACC_CONFIRM="DEALERMSG_THAWACC_CONFIRM|确定要进行解冻操作吗?";
//店铺装修金信息页面
var JSMSG_SHOP_NAME_AGAIN ="JSMSG_SHOP_NAME_AGAIN|店铺代码已存在!";
//开店提示信息
var SHOPMSG_DELETE_SELECTT ="SHOPMSG_DELETE_SELECTT|请选择要开哪一个店铺!";
//联络追加
var RECORDAPPEND_SELECT = "RECORDAPPEND_SELECT|请填写店铺/经销商代码";
var RECORDAPPEND_REPLID ="RECORDAPPEND_REPLID|请选择回电人";
//联络记录回复
var RECORDREPLAY_SELECT="RECORDREPLAY_SELECT|请选择哪条记录回复!"; 
var USERIDEXIST_ISEXIST="USERIDEXIST_ISEXIST|该用户不存在!";
var SELECT_GOODS_GOOD="SELECT_GOODS_GOOD|请选择商品明细!";
var ENSUER_GOODS_GOOD="ENSUER_GOODS_GOOD|您确定要调入吗?";
//判断装箱号
var SHIPMENTNO_EXIST="SHIPMENTNO_EXIST|输入的装箱号不存在,请核查!";
var SHIPMENTNO_ERROR="SHIPMENTNO_ERROR|该装箱号有多个状态，请联系系统部!"; 
var SHIPMENTNO_ISEXIST="SHIPMENTNO_ISEXIST|该装箱号已入库!";
var SHIPMENTPONO_PONO ="SHIPMENTPONO_PONO|该装箱号里有PO已入库，请联系系统部!";
var SHIPMENT_SELECT="SHIPMENT_SELECT|请选择哪一个要进行入库";
var NOTESELECT_DATA="NOTESELECT_DATA|没查到数据!";
var NOTWHCODE_RECORD="NOTWHCODE_RECORD|没有此店铺";
var STORAGESHOPNUM = "STORAGESHOPNUM|该装箱号有多个店铺，请联系系统部!";
var STORAGESHOPSAME="STORAGESHOPSAME|装箱号与所选的店铺不一致!";
var STORAGEEXTISSELECT ="STORAGEEXTISSELECT|没有数据,不可入库!";
var STORAGEUPDATE ="STORAGEUPDATE|您确定入库吗?";
var STORAGEENSUR_OTHRE="STORAGEENSUR_OTHRE|没有数据,保存失败!"
var CUURENTINVENT_STORAGE="CUURENTINVENT_STORAGE|因系统中数据量大，请【店铺/经销商代码】和【商品号】两者必须输入一个条件!"	
	
//采购促销设置 
var JSMSG_PROMOTIONSET_VAL_ENDDATE="JSMSG_PROMOTIONSET_VAL_ENDDATE|促销区间的开始时间必须小于结束时间!";
var JSMSG_PROMOTIONSET_VAL_BEGINDATE="JSMSG_PROMOTIONSET_VAL_BEGINDATE|促销区间的开始日期必须大于当天 日期 !";
var JSMSG_PROMOTIONSET_NO_GOODS="JSMSG_PROMOTIONSET_NO_GOODS|请添加促销店铺/经销商 和促销商品 !";
var JSMSG_PROMOTIONSET_ADD_GIVEGOODS="JSMSG_PROMOTIONSET_ADD_GIVEGOODS|赠品类促销只能添加一个商品,请删除多出的商品!";
var JSMSG_PROMOTIONSET_STOP_PROMO="JSMSG_PROMOTIONSET_STOP_PROMO|确定要中断该促销吗?";
var JSMSG_PROMOTIONSET_NO_FULLGIFT="JSMSG_PROMOTIONSET_NO_FULLGIFT|请配置满额礼!";
var JSMSG_PROMOTIONSET_FULLGIFT_NOPERCENT="JSMSG_PROMOTIONSET_FULLGIFT_NOPERCENT|请配置满额礼中的百分比!";
var JSMSG_PROMOTIONSET_PERCENT_FULL="JSMSG_PROMOTIONSET_PERCENT_FULL|满额礼配置百分比总和不能大于100!";
var JSMSG_PROMOTIONSET_PASS_PROMO="JSMSG_PROMOTIONSET_PASS_PROMO|确定审核通过该促销吗?"
//入库明细查询
var TIMESELECT_SELECT="TIMESELECT_SELECT|开始时间不能大于结束时间!";
//店铺装修保证金页面
var JSMSG_BAIL_DATEAMT_CHECK ="JSMSG_BAIL_DATEAMT_CHECK|保证金日期和保证金额两个项目必须同时为空或为非空!";

//装箱查看明细
var SHIPMENTNO_SELECT_DETIAL="SHIPMENTNO_SELECT_DETIAL|请选择要查看那一条明细!"; 
var YMSTORADJUST_TEXT ="YMSTORADJUST_TEXT|请填写商品代码和调整前的到期日期";
var STORAGEGOODSNAMEEXIST="STORAGEGOODSNAMEEXIST|此商品不存在!";
var DELETEEDIT ="DELETEEDIT|确定要删除吗?";
//其他出入库登录
var STORAGE_STARTNUM="STORAGE_STARTNUM|输入的数量大于库存数量或者到期库存数量!请重新输入(商品代码为{0})!";
var OTHERSTORAGE_LOGIN="OTHERSTORAGE_LOGIN|保存成功!";
var OTHERTORAGE_LOGIN_SELECT="OTHERTORAGE_LOGIN_SELECT|店铺改变后,表中追加数据会清空!还改变吗!";
var STORAGE_SUCCESS="STORAGE_SUCCESS|调入成功!";
var STORAGEBOTSHIPMENT="STORAGEBOTSHIPMENT|装箱状态为0,请稍后再试!";
//po登录页面
var JSMSG_POLOGIN_ACC_MONEY ="JSMSG_POLOGIN_ACC_MONEY|账户余额不足,请选用其他付款方式补足余款!";
var JSMSG_POLOGIN_INTE_OUT="JSMSG_POLOGIN_INTE_OUT|返利余额支付不能超过订单金额的50%!";
var JSMSG_POLOGIN_GOODS_NOTADD="JSMSG_POLOGIN_GOODS_NOTADD|请添加您要订购的商品!";
var JSMSG_POLOGIN_PAY_OUT ="JSMSG_POLOGIN_PAY_OUT|请修改您的支付金额,已超出{0}元!";
var JSMSG_POLOGIN_PAY_SHORT ="JSMSG_POLOGIN_PAY_SHORT|请修改您的支付金额,还需{0}元!";
var JSMSG_POLOGIN_PAY_BASELINE ="JSMSG_POLOGIN_PAY_BASELINE|您的订购金额不足  {0} 元,不能生成订单!";
var JSMSG_POLOGIN_HOUSE_NOSEL ="JSMSG_POLOGIN_HOUSE_NOSEL|请选择经销商（店铺）!";
var JSMSG_POLOGIN_PAY_BANKORIPS ="JSMSG_POLOGIN_PAY_BANKORIPS|银行支付和IPS支付不能同时选择";
//特殊po登录页面
var JSMSG_POLOGINHAND_DEANOOPEN="JSMSG_POLOGINHAND_DEANOOPEN|该经销商还未开户!";
var JSMSG_POLOGINHAND_HOUNOOPEN="JSMSG_POLOGINHAND_HOUNOOPEN|该特约店还未开户!";
var JSMSG_POLOGINHAND_NOHOUSE="JSMSG_POLOGINHAND_NOHOUSE|该特约店/经销商不存在!";
var JSMSG_POLOGINHAND_NO_POTYPE="JSMSG_POLOGINHAND_NO_POTYPE|请选择po类型 !";
var JSMSG_POLOGINHAND_GOODS_HAVEN="JSMSG_POLOGINHAND_GOODS_HAVEN|该商品已添加 !";
var JSMSG_POLOGINHAND_NOT_GOODS="JSMSG_POLOGINHAND_NOT_GOODS|该商品不存在 !";
var JSMSG_POLOGINHAND_NO_CONTENT="JSMSG_POLOGINHAND_NO_CONTENT|请填写要添加的商品编号!";
var JSMSG_POLOGINHAND_NO_HOUSE="JSMSG_POLOGINHAND_NO_HOUSE|请填写特约店/经销商并查询！";
var JSMSG_POLOGINHAND_NEED_ADDGOODS="JSMSG_POLOGINHAND_NEED_ADDGOODS|请 添加订购商品!";
var JSMSG_POLOGINHAND_PRICE_VAL="JSMSG_POLOGINHAND_PRICE_VAL|该PO类型下 商品单价必须为0!";
var JSMSG_POLOGINHAND_NO_POTYPE="JSMSG_POLOGINHAND_NO_POTYPE|PO类型不能为空!";
var JSMSG_POLOGINHAND_FILE_TYPE_ERR="JSMSG_POLOGINHAND_FILE_TYPE_ERR|请选择Excel文件";
var JSMSG_POVERIFY_ZB_CANCEL = "JSMSG_POVERIFY_ZB_CANCEL|您确定要拒绝该订单吗?";
	
	
// 退货登录
var JSMSG_RETURNGOODSLOGIN_DATEFROMTOCHECK="JSMSG_RETURNGOODSLOGIN_DATEFROMTOCHECK|退货期间查询开始日不能大于结束日!";
var JSMSG_RETURNGOODSLOGIN_IMPORTWHCODE="JSMSG_RETURNGOODSLOGIN_IMPORTWHCODE|请输入[特约店/经销商]代码!";
var JSMSG_RETURNGOODSLOGIN_ADDMESSAGE="JSMSG_RETURNGOODSLOGIN_ADDMESSAGE|请添加要保存或修改的信息!";
var JSMSG_RETURNGOODSLOGIN_CHARDEFICIENCY="JSMSG_RETURNGOODSLOGIN_CHARDEFICIENCY|条形码输入字符不足13位,请重新输入!";
var JSMSG_RETURNGOODSLOGIN_DATECHARDEFICIENCY="JSMSG_RETURNGOODSLOGIN_DATECHARDEFICIENCY|条形码到期日期输入字符不足6位,请重新输入!";
var JSMSG_RETURNGOODSLOGIN_DATECODENULL="JSMSG_RETURNGOODSLOGIN_DATECODENULL|条形码和商品代码,到期日期不能两方都为空!";
var JSMSG_RETURNGOODSLOGIN_NOTRETURNGOODS="JSMSG_RETURNGOODSLOGIN_NOTRETURNGOODS|该商品已经超过可退货期限，不能退货！";
var JSMSG_RETURNGOODSLOGIN_VALIDGOODSCODE="JSMSG_RETURNGOODSLOGIN_VALIDGOODSCODE|请输入有效的商品代码!";
var JSMSG_RETURNGOODSLOGIN_DONOTDELOREDIT="JSMSG_RETURNGOODSLOGIN_DONOTDELOREDIT|进度不是【退货已登录】的退货订单,无法进行【编辑】或【删除】操作!";
var JSMSG_RETURNGOODSLOGIN_CHECKGOODSQTY="JSMSG_RETURNGOODSLOGIN_CHECKGOODSQTY|退货数量不允许为空,请检查退货数量,并输入有效的数量!";
var JSMSG_RETURNGOODSLOGIN_DELROW="JSMSG_RETURNGOODSLOGIN_DELROW|您确认删除这行信息吗!";
var JSMSG_RETURNGOODSLOGIN_CHECKGRETURNTYPE="JSMSG_RETURNGOODSLOGIN_CHECKGRETURNTYPE|退货类型不允许为空,请选择!";
// 管理部金额确认
var JSMSG_RGMANAGECONFIRM_DELCON="JSMSG_RGMANAGECONFIRM_DELCON|您确认删除这组信息吗!";
var JSMSG_RGMANAGECONFIRM_CHECKGOODSPRICE="JSMSG_RGMANAGECONFIRM_CHECKGOODSPRICE|单价不允许为空,请检查单价,并输入有效的单价!";
var JSMSG_RGMANAGECONFIRM_CHECKGOODSQTY="JSMSG_RGMANAGECONFIRM_CHECKGOODSQTY|数量不允许为空,请检查数量,并输入有效的数量!";
var JSMSG_RGMANAGECONFIRM_CHECKWLQTY="JSMSG_RGMANAGECONFIRM_CHECKWLQTY|物流确认数量大于登录数量,请确认!";
var JSMSG_RGMANAGECONFIRM_CHECKMANAGEQTY="JSMSG_RGMANAGECONFIRM_CHECKMANAGEQTY|确认入库数量大于物流确认数量,请确认!";
// 会员注册
var JSMSG_MEMBERREGISTER_CHECKNAME="JSMSG_MEMBERREGISTER_CHECKNAME|姓名不允许为空!";
var JSMSG_MEMBERREGISTER_CHECKTEL="JSMSG_MEMBERREGISTER_CHECKTEL|请输入有效的手机号码!";
var JSMSG_MEMBERREGISTER_CHECKPOST="JSMSG_MEMBERREGISTER_CHECKPOST|请输入有效的邮编!";
var JSMSG_MEMBERREGISTER_CHECKDATELEN="JSMSG_MEMBERREGISTER_CHECKDATELEN|请输入10位有效的操作时间!";
var JSMSG_MEMBERREGISTER_REGISTERMESSAGE ="JSMSG_MEMBERREGISTER_REGISTERMESSAGE|注册{0}";
var JSMSG_MEMBERREGISTER_CHECKDATE ="JSMSG_MEMBERREGISTER_CHECKDATE|注册日期检索开始日不能大于注册日期检索结束日!";
var JSMSG_MEMBERORDERSEARCH_CHECKDATE ="JSMSG_MEMBERORDERSEARCH_CHECKDATE|订购日期检索开始日不能大于订购日期检索结束日!";
var JSMSG_MEMBERINFOSEARCH_CHECKWHCODE ="JSMSG_MEMBERINFOSEARCH_CHECKWHCODE|如需检索【其他店铺】,请先选择【店铺】!";
var JSMSG_MEMBERINFOSEARCH_CHECKOTHERWHCODE ="JSMSG_MEMBERINFOSEARCH_CHECKOTHERWHCODE|对不起,该【店铺】没有关联的【其他店铺】!";
var JSMSG_MEMBERINFOSEARCH_CHECKNULLWHCODE ="JSMSG_MEMBERINFOSEARCH_CHECKNULLWHCODE|请选择【店铺】或【其他店铺】!";
var JSMSG_MEMBERINFOSEARCH_CHECKPOINT ="JSMSG_MEMBERINFOSEARCH_CHECKPOINT|积分区间from不能大于积分区间to!";
var JSMSG_GOODSORDERSEARCH_CHECKWHCODELEN ="JSMSG_GOODSORDERSEARCH_CHECKWHCODELEN|商品编号第{0}个不能为空或长度不能大于10位,请确认!";
var JSMSG_GOODSORDERSEARCH_CHECKWHCODE ="JSMSG_GOODSORDERSEARCH_CHECKWHCODE|商品编号第{0}个不能为空或长度不能大于10位,第{1}个存在异常字符,请确认!";
var JSMSG_GOODSORDERSEARCH_CHECKWHCODECHAR ="JSMSG_GOODSORDERSEARCH_CHECKWHCODECHAR|商品编号第{0}个存在异常字符,请确认!";
var JSMSG_SAMPLEDISPATCHSEARCH_CHECKDATE ="JSMSG_SAMPLEDISPATCHSEARCH_CHECKDATE|派发期间检索开始日不能大于派发期间检索结束日!";
// 短信验证
var JSMSG_MEMBERVALID_CHECKMOCODE ="JSMSG_MEMBERVALID_CHECKMOCODE|对不起,您输入的验证码不正确。请重新输入!";
//返利余额添加
var JSMSG_FANLIGE_NO_GETLIST="JSMSG_FANLIGE_NO_GETLIST|请先读取文件!";
//积分明细查询
var JSMSG_NPDETAILSEARCH_CHECKDATE ="JSMSG_NPDETAILSEARCH_CHECKDATE|日期范围检索开始日不能大于日期范围检索结束日!";
var JSMSG_NPDETAILSEARCH_CHECKCUSTNO ="JSMSG_NPDETAILSEARCH_CHECKCUSTNO|请输入【会员号/顾客号/手机号】!";
var JSMSG_EXCHANGENP_COUPON ="JSMSG_EXCHANGENP_COUPON|请选择所要兑换的优惠券!";
// 销售结算单统计
var JSMSG_SALESTATEMENTS_CHECKDATE ="JSMSG_SALESTATEMENTS_CHECKDATE|结算日期检索开始日不能大于结算日期检索结束日!";
var JSMSG_MANAGEREPORTUPLOAD_MESSAGE ="JSMSG_MANAGEREPORTUPLOAD_MESSAGE|上传信息:{0}";
var JSMSG_REMITCONFIRMVIEW_CHECKDATE ="JSMSG_REMITCONFIRMVIEW_CHECKDATE|对象期间检索开始日不能大于对象期间检索结束日!";

var JSMSG_POQUERY_IPS_UNNEED="JSMSG_POQUERY_IPS_UNNEED|不存在IPS支付或IPS支付金额为0!";
var JSMSG_CONFIRM_ZB_HK_SHORT = "JSMSG_CONFIRM_ZB_HK_SHORT|汇款金额不能低于订单金额的{0}%";

//促销分配
var JSMSG_PROMOTIONDIS_NO_GDNO="JSMSG_PROMOTIONDIS_NO_GDNO|请选择批次?";	

//商品管理  采购基准价审核
var BUYPRICE_SELECT_SURE="BUYPRICE_SELECT_SURE|您确定批准吗?";
var BUYPRICE_LOOK_NOTSURE="BUYPRICE_LOOK_NOTSURE|您确定拒绝吗?";
var DEALTARAN_TAREAN="DEALTARAN_TAREAN|请选择要转移的店铺!";
//店铺分组
var SHOPPACKET_WHCODE="SHOPPACKET_WHCODE|请输入主特约店代码?";

//采购处理
var JSMSG_ORDERACCEPT_NUM_LOSE="JSMSG_ORDERACCEPT_NUM_LOSE|商品:{0} 数量不足不能置换组合!";
var JSMSG_ORDERACCEPT_POINT_LOSE="JSMSG_ORDERACCEPT_POINT_LOSE|当前可用积分不足";
var JSMSG_ORDERACCEPT_ORDERAMT_LOSE="JSMSG_ORDERACCEPT_ORDERAMT_LOSE|当前购买金额{0}小于该优惠券基准金额{1},不能使用优惠券";
var JSMSG_ORDERACCEPT_DELETE_PRESENT_GOODS="JSMSG_ORDERACCEPT_DELETE_PRESENT_GOODS|赠品不能直接删除!";
var JSMSG_ORDERACCEPT_RECEIVE_MONEY_ERROR="JSMSG_ORDERACCEPT_RECEIVE_MONEY_ERROR|商场实收金额不能大于应付金额!";
var JSMSG_ORDERACCEPT_POINT_IS_SHORT="JSMSG_ORDERACCEPT_POINT_IS_SHORT|订单使用积分已超出可用积分!";
var JSMSG_ORDERACCEPT_NO_CUSTOMER="JSMSG_ORDERACCEPT_NO_CUSTOMER|请先进行顾客选择!";
var JSMSG_ORDERACCEPT_PAYMONEY_BEYOND="JSMSG_ORDERACCEPT_PAYMONEY_BEYOND|支付金额不正确,已超出{0}元";
var JSMSG_ORDERACCEPT_PAYMONEY_SHORT="JSMSG_ORDERACCEPT_PAYMONEY_SHORT|支付金额不正确,还差{0}元";
var JSMSG_ORDERACCEPT_CLEAR_CONFIRM="JSMSG_ORDERACCEPT_CLEAR_CONFIRM|该订单尚未保存,是否保存？<br/>【确认】保存【取消】清除订单";
var JSMSG_ORDERACCEPT_CLOSE_CONFIRM="JSMSG_ORDERACCEPT_CLOSE_CONFIRM|该订单尚未保存,是否保存？<br/>【确认】保存 【取消】关闭页面";
var JSMSG_ORDERACCEPT_POINTASMONEY_BIG="JSMSG_ORDERACCEPT_POINTASMONEY_BIG|积分当钱花使用积分兑换金额不能超过订购总额金额的{0}";

var JSMSG_ORDERACCEPT_FULLGIFT_CONFIRM="JSMSG_ORDERACCEPT_FULLGIFT_CONFIRM|该订单满额礼不能全部提供,是否提交？<br/>【确认】提交【取消】查看订单";
var JSMSG_CHECK_SAMPLE_GOODS="JSMSG_CHECK_SAMPLE_GOODS|请添加开样商品！";


var JSMSG_CUSTOMERBUYLOG_NO_CUSTOMER="JSMSG_CUSTOMERBUYLOG_NO_CUSTOMER|请先进行顾客查询！";

var JSMSG_ORDERACCEPT_ORDERTIME_BEFORE="JSMSG_ORDERACCEPT_ORDERTIME_BEFORE|该优惠券尚未开始，不可使用！";
var JSMSG_ORDERACCEPT_ORDERTIME_AFTER="JSMSG_ORDERACCEPT_ORDERTIME_AFTER|该优惠券已经结束，不可使用！";
var JSMSG_ORDERACCEPT_ORDERSTATE_USED="JSMSG_ORDERACCEPT_ORDERSTATE_USED|该优惠券已使用，不可使用！";
var JSMSG_ORDERACCEPT_ORDERUSER_BELONG="JSMSG_ORDERACCEPT_ORDERUSER_BELONG|该优惠券不属于 {0}({1}/{2})，不可使用！";

var JSMSG_ORDERACCEPT_NO_SALESMAN="JSMSG_ORDERACCEPT_NO_SALESMAN|请先进行销售员选择!";
